name: Build

on:
  pull_request:
    branches:
      "master"
  push:
    branches:
      "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: chmod +x gradlew
      - run: ./gradlew clean test
#      - name: Copy History
#        uses: actions/checkout@v4
#        if: always()
#        with:
#          ref: gh-pages
#          path: gh-pages
#      - name: Build Report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        with:
#          allure_results: build/allure-results
#          allure_history: allure-history
#          keep_reports: 20
#      - name: Publish Report
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history